version: 0.2

phases:
  post_build:
    commands:
      - echo Generating imagedefinitions.json
      - echo '[{"name":"brain-tasks-app","imageUri":"075617906556.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
















































































