apiVersion: apps/v1
kind: Deployment
spec:
  containers:
    - name: brain-tasks-app
      image: 075617906556.dkr.ecr.us‑east‑1.amazonaws.com/brain-tasks-app:latest
metadata:
  name: brain-tasks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks
  template:
    metadata:
      labels:
        app: brain-tasks
    spec:
      containers:
        - name: brain-tasks
          image: heisenbergzz/dev:latest
          ports:
            - containerPort: 80
